# Generated by Django 4.2.7 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excedente',
            fields=[
                ('id_ex', models.AutoField(primary_key=True, serialize=False)),
                ('limite_minimo_ex', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_maximo_ex', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_ex', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion_ex', models.DateTimeField()),
                ('fecha_creacion_ex', models.DateTimeField()),
            ],
            options={
                'db_table': 'excedente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tar', models.CharField(max_length=500)),
                ('descripcion_tar', models.TextField()),
                ('estado_tar', models.CharField(max_length=25)),
                ('m3_maximo_tar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_basica_tar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_excedente_tar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_mora_tar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tarifa',
                'managed': False,
            },
        ),
    ]
