# Generated by Django 4.2.7 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_com', models.DateField()),
                ('mensaje_com', models.CharField(max_length=200)),
                ('actualizacion_com', models.DateTimeField()),
                ('creacion_com', models.DateTimeField()),
            ],
            options={
                'db_table': 'comunicado',
                'managed': False,
            },
        ),
    ]
