# Generated by Django 4.2.7 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id_imp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_imp', models.CharField(max_length=100)),
                ('descripcion_imp', models.TextField()),
                ('porcentaje_imp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retencion_imp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_imp', models.CharField(max_length=50)),
                ('creacion_imp', models.DateTimeField()),
                ('actualizacion_imp', models.DateTimeField()),
            ],
            options={
                'db_table': 'impuesto',
                'managed': False,
            },
        ),
    ]
