# Generated by Django 4.2.7 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asi', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_asi', models.CharField(max_length=100)),
                ('valor_asi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atraso_asi', models.CharField(max_length=25)),
                ('valor_atraso_asi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creacion_asi', models.DateTimeField()),
                ('actualizacion_asi', models.DateTimeField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
    ]
