# Generated by Django 4.2.7 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_per', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_per', models.CharField(max_length=50)),
                ('descripcion_per', models.TextField()),
                ('estado_per', models.CharField(max_length=50)),
                ('creacion_per', models.DateTimeField()),
                ('actualizacion_per', models.DateTimeField()),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('apellido_usu', models.CharField(max_length=150)),
                ('nombre_usu', models.CharField(max_length=150)),
                ('email_usu', models.CharField(max_length=150)),
                ('password_usu', models.CharField(max_length=500)),
                ('estado_usu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
