# Generated by Django 4.2.7 on 2025-02-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id_consumo', models.AutoField(primary_key=True, serialize=False)),
                ('anio_consumo', models.IntegerField()),
                ('mes_consumo', models.CharField(max_length=20)),
                ('estado_consumo', models.CharField(max_length=20)),
                ('fecha_creacion_consumo', models.DateTimeField()),
                ('fecha_actualizacion_consumo', models.DateTimeField()),
                ('numero_mes_consumo', models.IntegerField()),
                ('fecha_vencimiento_consumo', models.DateField()),
            ],
            options={
                'db_table': 'consumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
                ('numero_med', models.CharField(max_length=50)),
                ('serie_med', models.CharField(max_length=100)),
                ('marca_med', models.CharField(max_length=100)),
                ('observacion_med', models.TextField()),
                ('estado_med', models.CharField(max_length=25)),
                ('foto_med', models.CharField(max_length=500)),
                ('creacion_med', models.DateTimeField()),
                ('actualizacion_med', models.DateTimeField()),
                ('lectura_inicial_med', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'medidor',
                'managed': False,
            },
        ),
    ]
